import sqlite3
con=sqlite3.connect('db1.db')
c=con.cursor()
#c.execute('create table employee(emplid number Not null ,name text,salary number,Primary key emplid)')
c.execute('insert into employee values(1,"saniya",10000)')
c.execute('insert into employee values(2,"tina",15000)')
c.execute('insert into employee values(3,"ali",20000)')
c.execute('insert into employee values(4,"ram",17000)')
con.commit()
c.execute('select * from employee')
data=c.fetchall()
print(data)
c.close()
con.close()
