import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([[1,2],[3,4]])
z=np.array([[[1,2],[3,4],[5,6]]])
print(x)
print("xdimension:",x.ndim)
print("ydimension:",y.ndim)
print("zdimension:",z.ndim)
print(y)
print(z)
print("shape of x:",x.shape)
print("shape of y:",y.shape)
print("shape of z:",z.shape)
